frontend/src/components/QuestionsList.tsx

Due to insufficient testing it was missed that add actions button no
longer displays on Workshop and Follow-up tabs due to changes made in
15acdfcf6ae69a4d51e2c814e5bd59c761c700ea
No UI tests unfortunately are added yet, which creates high uncertainty with regards to whether current change breaks something else or not, so we need to find feasible solution soon.
Frameworks are good, but we need to figure out what can be  done with authentication (bypass, mock, use custom users?) and how to do that.
closes #455

Bring back ability to add actions

---

backend/api/GQL/Mutation.cs
backend/api/Migrations/20210719094100_PreviousEvaluationId.Designer.cs
backend/api/Migrations/20210719094100_PreviousEvaluationId.cs
backend/api/Models/Models.cs
backend/api/Services/EvaluationService.cs
backend/tests/GQL/Mutation.cs
backend/tests/Services/AnswerService.cs
backend/tests/Services/EvaluationService.cs
backend/tests/Services/ParticipantService.cs
backend/tests/Services/QuestionService.cs
frontend/cypress/integration/create_evaluation_spec.ts
frontend/cypress/integration/sample_seed.ts
frontend/cypress/support/evaluation_seed.ts
frontend/cypress/support/helpers.ts
frontend/cypress/support/project.ts
frontend/src/api/fragments.ts
frontend/src/api/models.ts
frontend/src/views/Project/Dashboard/CreateEvaluationButton.tsx
frontend/src/views/Project/Dashboard/CreateEvaluationDialog.tsx
frontend/src/views/Project/Dashboard/ProjectDashboardGQL.ts

Give users the option to add a link to a previous evaluation when
creating a new evaluation. For now this link is not used anywhere else
in the frontend.
Run `dotnet ef database update` on dev database after merging
Closes #446

Link previous evaluation

---

frontend/src/utils/QuestionAndAnswerUtils.test.ts
frontend/src/utils/QuestionAndAnswerUtils.ts

**Context**: In all steps of BMT, there is a side panel next to the questions that count how many questions are answered. The Workshop tab works a bit different than the other tabs, because here only facilitators can write answers, and if there are more than one facilitator, there can be answers from either of these on either of the questions.
**Problem**: Even though multiple respondents can answer the questions, in the side panel, only the answers written by the logged in user will be counted. Therefore, we can easily get a situation where you can see that 10 out of 37 questions is answered, but in the side panel it only says that 1/37 questions are answered.
**Solution**: For the Workshop tab (`Progression.Workshop` in the code), we have to count all answers, not only the answers that …

Progress indicator in workshop tab now counts all answers

---

README.md
backend/api/Startup.cs

It's been decided that the best way to locally disable authorization for
development is to locally comment it out every time it is needed.
It has been considered a safer way than introducing an environment
variable to do so.

Document disabling authorization for development

---

frontend/src/components/AnswerSummarySidebar.tsx
frontend/src/utils/RoleBasedAccess.ts

This commit prohibits participants with role Participant or ReadOnly to
view other participants individual answers in the AnswerSummarySidebar.
Closes #470

Add role-based access to answers

---

frontend/src/utils/RoleBasedAccess.ts
frontend/src/views/Evaluation/Nomination/NominationTable.tsx
frontend/src/views/Evaluation/Nomination/NominationView.tsx

This PR solves several issues with who and when different actions could be performed in the Nomination step. It formalises the privilege of Adding new Participants, deleting participants and progressing the evaluation past the Nomination stage:
- **Add Participant**:  `Facilitator` and `OrganizationLead` can add participants, regardless of which progression the Evaluation is at.
- **Delete Participants**: `Facilitators` and `OrganizationLead` can delete participants, but only when the Evaluation is still at `Nomination`.
- **Progress Evaluation**: `Facilitators` can progress evaluation from `Nomination` to `Individual`.
Additional safeguards are added to restrict non-members of the Evaluation from performing any of the above mutations. That was possible prior to this PR.

Update Role privileges at Nomination step

---

frontend/src/components/Action/QuestionActionsList.tsx
frontend/src/components/ActionTable/ActionTable.tsx
frontend/src/components/ActionTable/ActionTableForOneUserWithApi.tsx
frontend/src/components/ActionTable/ActionTableWithApi.tsx

**The bug**: In the action list on either the Dashboard (1), or in the Follow-up tab (2),
(1)
(2)
when clicking on an action to open it in the side panel, and then writing a note, the note will not appear in the list of notes beneath the input field, even though the saved icon appears and the note seems to be saved. This problem does not happen when opening an action in the side panel in the questions view (3)
(3)
**This fix:** The problem was that we were sending a copy of the action to the side panel, and this copy had the old list of notes which then would not list the new note. Now, the action in the side panel is refreshed every time the component is refreshed, and will thus have the newest data.

Fixed bug where new note was not listed

---

backend/api/GQL/Mutation.cs
backend/api/Services/AnswerService.cs
backend/tests/Services/AnswerService.cs

This commit corrects an issue where some older evaluation configurations
could provoke a uniqueness violation in the database. Ultimately
resulting in the end-user being unable to update an answer.
The uniqueness requirement for an entry in the dB's Answer table is that
the combination of the fields QuestionId, Progression, and AnsweredById
must be unique. This requirement is broken in older evaluations where
there are recorded several answers for the same Progression (Workshop or
Follow-up).
In the current production code, which support shared answers, the first
answer recorded at Workshop or Follow-up is shared among all users
(Facilitators). In effect there exist only a single answer for a
question in Workshop and Follow-up. However, in evaluations created
prior to the introduction of …

Don't update author on shared answers

---

frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
frontend/src/components/QuestionAndAnswer/QuestionAndAnswerFormWithApi.tsx

Problem: In the main question form, when saving (only) severity on an answer and then quickly changing barrier or progression, the severity is often not saved.
Solution: The problem was that we have a delay before saving that is used when writing an answer text, so that we don't fire a graphQL mutation for every letter written. Since severity and text are both attributes on an Answer, the delay automatically applied for severity as well. I am now saving these to values in different variables so that the delay only applies to the text and not severity.

Fixed slow saving of severity

---

backend/api/Authorization/AuthService.cs
backend/api/GQL/Mutation.cs
backend/tests/DbContextTestSetup.cs
backend/tests/GQL/Mutation.cs
backend/tests/GQL/Mutations/CreateAction.cs
backend/tests/GQL/Mutations/CreateClosingRemark.cs
backend/tests/GQL/Mutations/CreateNote.cs
backend/tests/GQL/Mutations/CreateParticipant.cs
backend/tests/GQL/Mutations/DeleteAction.cs
backend/tests/GQL/Mutations/DeleteParticipant.cs
backend/tests/GQL/Mutations/EditAction.cs
backend/tests/GQL/Mutations/ProgressEvaluation.cs
backend/tests/GQL/Mutations/ProgressParticipant.cs
backend/tests/GQL/Mutations/SetAnswer.cs
backend/tests/GQL/Mutations/SetSummary.cs
backend/tests/Randomize.cs
frontend/cypress/integration/actions_spec.ts
frontend/cypress/support/evaluation_seed.ts
frontend/cypress/support/testdata.ts
frontend/src/api/models.ts

This PR adds role-based restrictions to all exposed mutations. Additionally it extends the current test-framework to test the new restrictions.
The test framework for Mutation testing in the backend only implements access-based tests at the moment, but it is intended to be used for further correctness testing of the mutations. However that is out of scope of this PR.
Closes #537
Closes #512

Add Role-based restriction to backend mutations

---

frontend/src/components/Action/EditForm/ActionEditForm.tsx
frontend/src/components/Action/EditForm/ActionEditSidebar.tsx
frontend/src/components/Action/QuestionActionsList.tsx
frontend/src/components/QuestionItem.tsx
frontend/src/components/QuestionsList.tsx
frontend/src/components/helpers.ts
frontend/src/globals/contexts.ts
frontend/src/utils/QuestionAndAnswerUtils.ts
frontend/src/utils/RoleBasedAccess.ts
frontend/src/utils/disableComponents.ts
frontend/src/views/Evaluation/EvaluationView.tsx
frontend/src/views/Evaluation/FollowUp/FollowUpView.tsx
frontend/src/views/Evaluation/Individual/IndividualView.tsx
frontend/src/views/Evaluation/Nomination/NominationTable.tsx
frontend/src/views/Evaluation/Nomination/NominationView.tsx
frontend/src/views/Evaluation/Preparation/PreparationView.tsx
frontend/src/views/Evaluation/Workshop/WorkshopSummary.tsx
frontend/src/views/Evaluation/Workshop/WorkshopSummaryWithApi.tsx
frontend/src/views/Evaluation/Workshop/WorkshopTabs.tsx
frontend/src/views/Evaluation/Workshop/WorkshopView.tsx

Changes in this PR:
* A participant who is not a part of an evaluation is now `undefined`. This means that `useParticipant()` now returns either a `Participant` or an `undefined`.
* Some of the functions that have had `azureUniqueId` as an argument now has a participant as an argument. This makes it possible to check if a participant is `undefined` before the id of the participant is being used.
* There has been created functions that deal with access to various components and operations. Some of these functions replace boolean expressions that were difficult to read, and some of them present new functionality that ensure that an `undefined` participant cannot do any operations in an evaluation. For instance, an `undefined` participant cannot delete, add or edit actions.
* Everyone, …

Allow everyone to view all evaluations

---

frontend/cypress/integration/actions_spec.ts
frontend/cypress/support/evaluation_seed.ts
frontend/src/utils/RoleBasedAccess.ts

Initial state in database is set in beforeEach for each test.
The the test data used in the test is retrieved or created in the test itself.

Revise actions test

---

frontend/src/views/Admin/AdminView.tsx
frontend/src/views/Admin/BarrierSidebar.tsx
frontend/src/views/Project/ProjectRoute.tsx

Almost nothing added to this PR. Now looks like this:
There is no permissions restrictions on seeing this tab right now. Maybe I should fix that as part of this PR.

Initial admin view

---

backend/api/GQL/Query.cs
backend/tests/GQL/Query.cs
frontend/src/api/fragments.ts
frontend/src/api/models.ts
frontend/src/views/Admin/AdminQuestionItem.tsx
frontend/src/views/Admin/AdminView.tsx
frontend/src/views/Admin/BarrierQuestionList.tsx
frontend/src/views/Admin/QuestionListWithApi.tsx

With this PR, the admin view now looks like this
In addition to the changes in the frontend, it is now possible to query for `QuestionTemplate`.

Add list of questions to each barrier in admin page

---

backend/api/Context/BmtDbContext.cs
backend/api/Context/InitContent.cs
backend/api/GQL/Mutation.cs
backend/api/GQL/Query.cs
backend/api/Migrations/20210915135241_AddProjectCategory.Designer.cs
backend/api/Migrations/20210915135241_AddProjectCategory.cs
backend/api/Models/Models.cs
backend/api/Services/ProjectCategoryService.cs
backend/api/Services/QuestionTemplateService.cs
backend/api/Startup.cs
backend/tests/DbContext.cs
backend/tests/GQL/Mutation.cs
backend/tests/GQL/Mutations/CreateEvaluation.cs
backend/tests/GQL/Query.cs
backend/tests/Randomize.cs
backend/tests/Services/ProjectCategoryService.cs
backend/tests/Services/QuestionTemplateService.cs
frontend/cypress/integration/create_evaluation_spec.ts
frontend/cypress/integration/sample_spec.ts
frontend/cypress/support/evaluation_seed.ts
frontend/cypress/support/gql.ts
frontend/cypress/support/project.ts
frontend/src/api/models.ts
frontend/src/utils/QuestionAndAnswerUtils.test.ts
frontend/src/views/Project/Dashboard/CreateEvaluationButton.tsx
frontend/src/views/Project/Dashboard/CreateEvaluationDialog.tsx

This PR introduces a new table "Sub Project" in our database. A sub project is essentially a set of QuestionTemplates. In the real world a subproject might be "GreenField" or "BrownField". There is many-to-many relationship between subproject and questionTemplates. I.e. a subproject contains many questionTemplates, but a questionTemplate can also used in multiple subprojects.
The subprojects are put to use in the CreateEvaluationDialog, where it's now mandatory to choose which sub project (questionnaire set) to use in the evaluation.
Additionally, several new mutations that will become useful in the new admin module is added. Authorisation mechanisms for the admin queries/mutations are not yet added
Closes #602 
Closes #604 
Closes #605
Closes #606

Prepare backend for admin module

---

frontend/src/components/Action/EditForm/ActionEditSidebar.tsx
frontend/src/components/QuestionAndAnswer/QuestionAndAnswerFormWithApi.tsx
frontend/src/views/Admin/AdminQuestionItem.tsx
frontend/src/views/Admin/AdminView.tsx
frontend/src/views/Admin/BarrierMenu.tsx
frontend/src/views/Admin/EditableQuestionItem.tsx
frontend/src/views/Admin/QuestionListWithApi.tsx
frontend/src/views/Admin/QuestionTemplateMenu.tsx
frontend/src/views/Admin/StaticQuestionItem.tsx
frontend/src/views/Evaluation/Workshop/WorkshopSummaryWithApi.tsx
frontend/src/views/helpers.ts

With this pull request it will be possible to add and remove a project category label to/from a question template (i.e. add/ remove question template from project category). The view looks like this:
By clicking the menu element next to the Barrier name, all questions in the barrier are made editable. It is now possible to select or deselect elements from the dropdown. Every selection triggers one API-call, either to add or remove.
**Features of this PR:**
* Frontend for adding and deleting as described above
* GraphQL mutations for adding and deleting
* Save-indicator on each question when saving
* Error message if saving fails
* Caching of results
* I also made a helper for some code that was used in several components, and used the helper in these "old" components as well
**Known …

Add / remove project category label to/from question template

---

frontend/src/api/fragments.ts
frontend/src/views/Admin/AdminQuestionItem.tsx
frontend/src/views/Admin/AdminView.tsx
frontend/src/views/Admin/Components/CancelOrSaveQuestion.tsx
frontend/src/views/Admin/Components/ErrorSavingQuestion.tsx
frontend/src/views/Admin/CreateQuestionItem.tsx
frontend/src/views/Admin/EditableQuestionItem.tsx
frontend/src/views/Admin/QuestionListWithApi.tsx
frontend/src/views/Admin/StaticQuestionItem.tsx
frontend/src/views/helpers.ts

The goal of this PR is to make it possible to add a new question template to a barrier. The component that is used to do this is quite similar to the component `EditableQuestionItem`, and consequently some refactoring has been done to avoid code duplication. Since a new question template does not belong to any project categories, the mutation that is used to create a question template cannot use the existing fragment for question templates, and consequently a new fragment has been made.

Add new question template

---

frontend/cypress/integration/actions_spec.ts
frontend/src/components/Action/EditForm/ActionEditForm.tsx

Confirm-button is now disabled if no comment is written. Also fixed cypress-tests to fit the change.

Closing remark is now mandatory when closing an action

---

backend/api/GQL/Mutation.cs
frontend/src/api/models.ts
frontend/src/utils/hooks.ts
frontend/src/views/Admin/AdminQuestionItem.tsx
frontend/src/views/Admin/AdminView.tsx
frontend/src/views/Admin/BarrierMenu.tsx
frontend/src/views/Admin/CreateProjectCategorySidebar.tsx
frontend/src/views/Admin/CreateQuestionItem.tsx
frontend/src/views/Admin/StaticQuestionItem.tsx

**Issue**: Make it possible to create a new project category through the admin panel.
**The solution flow:**
1) Click "Add project category" button at the top right
2) In the side panel that opens, type a name for the project category. It is not possible to click the save-button if the field is empty, and if the field is erased after typing something, the field will get an error message in addition to the disabled save-button. It is also possible to select a project category in the field below, but let's look at that later. After typing a name, click save.
3) After clicking save, the side panel will close, and the new project category will be selected in the project category dropdown. Since the category doesn't have any questions yet, a message will be visible, describing how to get …

Create new project category

---

frontend/src/components/ConfirmationDialog.tsx
frontend/src/views/Admin/CategoryHeader.tsx
frontend/src/views/Admin/Components/ErrorMessage.tsx

Looks like this:
Includes:
* Error handling (the Error box can now be closed if the component that uses it provides an onClose-function)
* A spinner in the confirmation box while saving if the component that uses it provides a loading-variable

Now possible to delete project category

---

frontend/cypress/integration/actions_spec.ts
frontend/cypress/integration/workshop_assessment_spec.ts
frontend/cypress/page_objects/action.ts
frontend/cypress/page_objects/common.ts
frontend/cypress/page_objects/workshop_assessment.ts
frontend/cypress/support/commands/visit.ts
frontend/cypress/support/testsetup/evaluation_seed.ts
frontend/src/components/Disabler.tsx
frontend/src/views/Evaluation/Workshop/WorkshopSummaryWithApi.tsx
frontend/src/views/Evaluation/Workshop/WorkshopTabs.tsx

Solves #534 
(1) The function `logInUser` I got from actions.ts. Not sure there is a better way to 'import' a function from cypress test.
(2) Having difficulties to test the disabler_box:
In the first test (Facilitator), none of these works, but maybe it is not necessary to test the disabler box anyway:
```
const disabler_box = cy.getByDataTestid('workshop_summary_div').within(() => {
cy.getByDataTestid('disabler_box_div')
})
expect(disabler_box).to.have.attr('display', 'none')
expect(disabler_box).to.have.css('display', 'none')
disabler_box.should('have.css', 'display', 'none')
disabler_box.should('be.hidden')
```
In addition, it does not raise an error with the following (which is the test run in the test for Participant, but for Facilitator should be `none`).
` …

Facilitator (other users) can (not) view/edit content on workshop summary tab

---

frontend/src/views/Admin/Components/QuestionTemplateButtons.tsx

Bugfix: QT buttons now stays on same line

---

frontend/cypress/integration/landing_page_spec.ts
frontend/cypress/support/testsetup/evaluation_seed.ts
frontend/cypress/support/testsetup/gql.ts

Refactored landing page tests and added tests for hidden (voided) evaluations.
With refactoring tests run much faster (25-30 s for 23 tests) for more tests than before (40 s for 13 tests)

Add test hidden evals are displayed in hidden tab

---

frontend/cypress/support/mock/external/projects.ts
frontend/src/api/fragments.ts
frontend/src/utils/hooks.ts
frontend/src/views/Project/Dashboard/Portfolios.tsx
frontend/src/views/Project/Dashboard/ProjectDashboardView.tsx

The hook to get portfolios is changed to optimize loading time, and handle async calls, but the original logic for where to find portfolio is maintained. Needs to be tested because it's difficult to know if the portfolios are correct.

New view for portfolios

---

frontend/src/views/Evaluation/EvaluationView.tsx
frontend/src/views/Evaluation/Nomination/AddNomineeDialog.tsx
frontend/src/views/Evaluation/Nomination/NominationView.tsx
frontend/src/views/Project/Dashboard/CreateEvaluationDialog.tsx
frontend/src/views/Project/Dashboard/EvaluationsTable.tsx
frontend/src/views/Project/Dashboard/ProjectDashboardView.tsx
frontend/src/views/Project/ProjectRoute.tsx

Inital suggestion to which elements it should be possible to comment on, on the following pages:
* Dashboard - evaluations list
* Create Evaluation View
* Nomination view
I have wrapped the elements I would have pointed to if I were to explain the application to somebody new, and omitted every button and text field that felt self-explanatory (i.e. finish nomination). However, if a button is self explanatory, but it seems uncertain what will happen after the action is performed, I have aimed to also wrap these elements.

Initial selection of quickfact-enabled items

---

pipelines/ArtifactBuild.yml
pipelines/templates/stage-trigger-radix.yml

To avoid identical id for the deployment step and to ensure radix builds
correct environment we send in branch as parameter. #869

Adding branch to template for radix trigger

---

frontend/cypress/integration/landing_page_spec.ts

Ready for review.
It can't be guaranteed that stability issue is solved, but at least it's not made worse - out of 80 runs in 4 batches there were no failures.

Stabilize failing landing spec test

---

frontend/cypress/page_objects/project.ts
frontend/src/components/ErrorBanner.tsx
frontend/src/utils/hooks.ts
frontend/src/views/Project/Dashboard/Components/CreateEvaluationButton.tsx
frontend/src/views/Project/Dashboard/Components/CreateEvaluationDialog.tsx
frontend/src/views/Project/Dashboard/DashboardView.tsx

- Started to use a new error display for errors in smaller views: ` <ErrorBanner/>`. This will be instead of the grey text fields we have been using until now:
Earlier:
Now:
- The error display is also moved. Earlier, if creating an evaluation didn't succeed, the sidebar would close, and the old error display would replace the "Create Evaluation"-button on the Dashboard. Now, the error banner will appear in the sidebar, making it possible to try again without losing the typed data. 
Earlier:
Now:
- Removed the text explaining that it's difficult to remove a created evaluation, since we now have the possibility to hide an evaluation.
- Started using the same validation as in other forms in the application. I.e. warning message in the Input-component, instead of a free text next to the …

Made some changes to the CreateEvaluationDialog-view, to comply with the way the UI looks and acts in the rest of the application.

---

frontend/src/views/Project/Dashboard/Components/EvaluationsTable.tsx

**Problem**: The bowtie seemingly didn't render any "dots" if all the dots were green
**The real problem:** The evaluation with only green dots was finished, and we didn't take finished evaluations into account when we made the bowtie, because the concept didn't exist yet. Thus, we said to only render the bowtie on the progressions Workshop and FollowUp. 
**The solution:** We now render bowtie on Workshop and FollowUp and Finished, and select the questions from FollowUp when finished.

Bugfix: Bowtie now also renders on finished evaluations

---

frontend/cypress/integration/evaluation_spec.ts
frontend/src/views/Project/Dashboard/Components/CreateEvaluationButton.tsx

Commented out failing tests after talking with Petter. He will change the tests after merge.

Only admins can create evaluations

---

frontend/src/views/Evaluation/FollowUp/Views/Questionaire/FollowUpView.tsx
frontend/src/views/Evaluation/Preparation/PreparationView.tsx
frontend/src/views/Evaluation/Workshop/Questionaire/WorkshopView.tsx

To avoid the outer scrollbar, the inner div is set to a height that needs to be precisely the height of the view. This is calculated by fetching the heights and margins of some of the view elements, but for some reason the scroll bar got smaller, but didn't disappear. In this PR I simply added one pixel to the height, which made it finally disappear.
Before:
After: 
Could be smart to pull this down to test, in case it only works on my machine.

Removed outer scrollbar in questionnaire
