equinor/fusion-bmt

README.md, backend/api/Context/InitContent.cs, backend/api/GQL/Mutation.cs, backend/api/Models/Models.cs, backend/api/Services/AnswerService.cs, backend/api/Services/EvaluationService.cs, backend/api/Services/Exceptions.cs, backend/api/Services/ParticipantService.cs, backend/api/Services/ProjectService.cs, backend/api/Services/QuestionService.cs, backend/api/api.csproj, backend/tests/Services/AnswerService.cs, backend/tests/Services/EvaluationService.cs, backend/tests/Services/ParticipantService.cs, backend/tests/Services/ProjectService.cs, backend/tests/Services/QuestionService.cs
=> New services, update readme

README.md, backend/api/GQL/Query.cs, backend/api/Startup.cs, backend/api/api.csproj
=> Upgrade HotChocolate to V11

backend/api/GQL/Mutation.cs, backend/api/Services/EvaluationService.cs, backend/api/Services/Exceptions.cs, backend/api/Services/ServiceUtil.cs, backend/tests/Services/AnswerService.cs, backend/tests/Services/EvaluationService.cs, backend/tests/Services/ParticipantService.cs, backend/tests/Services/ProjectService.cs, backend/tests/Services/QuestionService.cs, backend/tests/Services/ServiceUtil.cs
=> Progress evaluations

backend/tests/DbContext.cs
=> DB context tests

backend/Dockerfile
=> Change Docker base image to fix runtime error

backend/api/Startup.cs, backend/api/api.csproj, backend/api/appsettings.json, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/config.ts, frontend/src/index.tsx, frontend/webpack.config.js, radixconfig.yaml
=> Add Application Insights to backend and frontend

azure-pipelines.yml, backend/Dockerfile, backend/api/api.csproj, backend/scripts/scripts.csproj, backend/tests/tests.csproj
=> Update to version 5 of .net

backend/api/Context/BmtDbContext.cs, backend/api/GQL/Mutation.cs, backend/api/Services/QuestionService.cs, backend/tests/Services/QuestionService.cs, scripts/create_json/create_json.py
=> Question bulk service

azure-pipelines.yml, backend/api/Authorization/AuthService.cs, backend/api/GQL/Mutation.cs, backend/tests/DbContext.cs
=> Allow only facilitator to change progression of evaluation

frontend/src/components/AnswerSummarySidebar.tsx, frontend/src/components/BarrierQuestionsView.tsx, frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx, frontend/src/utils/ProgressionStatus.test.ts, frontend/src/utils/ProgressionStatus.ts, frontend/src/views/Evaluation/Alignment/AlignmentView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopView.tsx
=> Display all answers in answer summary

backend/api/GQL/ErrorFilter.cs, backend/api/GQL/Mutation.cs, backend/api/GQL/Query.cs, backend/api/Program.cs, backend/api/Services/ProjectService.cs, backend/api/Startup.cs, backend/api/api.csproj, backend/tests/DbContext.cs, backend/tests/DbContextTestSetup.cs, backend/tests/GQL/Mutation.cs, backend/tests/GQL/Query.cs, backend/tests/Services/ProjectService.cs
=> Set up logging, more GQL tests

frontend/src/index.tsx
=> Select correct context from URL

backend/api/GQL/Mutation.cs, backend/api/GQL/Query.cs, backend/api/Services/ActionService.cs, backend/api/Services/NoteService.cs, backend/tests/DbContext.cs, backend/tests/GQL/Mutation.cs, backend/tests/GQL/Query.cs, backend/tests/Services/ActionService.cs, backend/tests/Services/NoteService.cs
=> Add action and note services, mutations, querys and tests

backend/api/appsettings.json, backend/tests/StartupTest.cs, backend/tests/tests.csproj
=> Test startup.cs and swagger

backend/api/Context/InitContent.cs, backend/api/Migrations/20210114083549_AddStatusToEvaluation.Designer.cs, backend/api/Migrations/20210114083549_AddStatusToEvaluation.cs, backend/api/Models/Models.cs, backend/api/Services/EvaluationService.cs, backend/api/Services/ServiceUtil.cs, backend/api/Startup.cs, backend/tests/DbContext.cs, backend/tests/Services/AnswerService.cs, backend/tests/Services/ParticipantService.cs, backend/tests/Services/ServiceUtil.cs, frontend/src/api/models.ts, frontend/src/components/AnswerSummarySidebar.tsx, frontend/src/components/ProgressEvaluationDialog.tsx, frontend/src/utils/EnumToString.ts, frontend/src/utils/ProgressionStatus.test.ts, frontend/src/utils/ProgressionStatus.ts, frontend/src/utils/QuestionAndAnswerUtils.test.ts, frontend/src/views/Evaluation/EvaluationView.tsx, frontend/src/views/Evaluation/Individual/IndividualView.tsx, frontend/src/views/Evaluation/IndividualAssessment/IndividualAssessmentView.tsx, frontend/src/views/Evaluation/Preparation/PreparationView.tsx, frontend/src/views/Project/Dashboard/EvaluationListItem.tsx
- Hard code backend url for compatibility
- Rename Preparation -> Individual Assessment
- Rename Alignment -> Preparation
- rename Workshop -> Workshop Aassessment
closes #267
=> Rename steps in an evaluation

backend/api/Context/InitContent.cs, backend/api/GQL/Mutation.cs, backend/api/Migrations/20210119100500_DateTimeOffset.Designer.cs, backend/api/Migrations/20210119100500_DateTimeOffset.cs, backend/api/Models/Models.cs, backend/api/Services/ActionService.cs, backend/api/Services/AnswerService.cs, backend/api/Services/EvaluationService.cs, backend/api/Services/NoteService.cs, backend/api/Services/ParticipantService.cs, backend/api/Services/ProjectService.cs, backend/api/Services/QuestionService.cs, backend/api/Services/QuestionTemplateService.cs, backend/scripts/DbHandler.cs, backend/tests/Services/ActionService.cs
=> DB change from datetime to datetimeoffset

frontend/src/components/Action/QuestionActionsList.tsx, frontend/src/components/AnswerSummaryButton.tsx, frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx, frontend/src/components/QuestionAndAnswer/QuestionAndAnswerFormWithApi.tsx, frontend/src/views/Evaluation/FollowUp/FollowUpView.tsx, frontend/src/views/Evaluation/Preparation/PreparationView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopView.tsx
=> Align action list

.gitignore, README.md, pipelines/deploy-fusion-ci.yml, pipelines/deploy-fusion-prod.yml, radixconfig.yaml
=> Add test environment

backend/Dockerfile, frontend/Dockerfile
=> Add non-root to docker images for added security

pipelines/deploy-fusion-ci.yml, pipelines/deploy-fusion-prod.yml
- Auto apply migrations when pushing to prod
- install dotnet-ef
closes #301
=> Auto apply migrations when pushing to prod

backend/api/.editorconfig, backend/api/Services/EvaluationService.cs, backend/api/Startup.cs, backend/api/api.csproj, backend/tests/tests.csproj
=> Add health endpoint to check if backend and db is running

README.md, backend/scripts/DbHandler.cs, backend/scripts/Program.cs
=> Scripts for ordering questions and question templates

backend/api/GQL/Mutation.cs, backend/api/Services/AnswerService.cs, backend/tests/Services/AnswerService.cs, frontend/src/components/QuestionItem.tsx, frontend/src/components/QuestionsList.tsx, frontend/src/components/SingleAnswerSummary.tsx, frontend/src/components/helpers.ts
Important note: The behaviour when 2 or more facilitators are editing the same answer _at the same time_ is undefined. There is also no warning issued to the users about this
=> Let facilitators share answers in workshop/followup

backend/api/Startup.cs
This commit fixes an issue with the backend setup that resulted in us
exposing endpoints without authorization.
=> Require authorization on exposed endpoints

frontend/src/components/QuestionsList.tsx, frontend/src/utils/QuestionAndAnswerUtils.ts, frontend/src/views/Evaluation/FollowUp/FollowUpView.tsx, frontend/src/views/Evaluation/Preparation/PreparationView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopView.tsx, frontend/src/views/helpers.ts
=> Fix synchronization of AnswerSummarySideBar when scrolling

frontend/src/views/Evaluation/Individual/IndividualView.tsx
Closes #463 
The commit statement seems slightly long, happy to change if needed.
@ReedOnly it would be informative if we could review it together, in case it is not the expected behaviour I can get direct feedback. Thanks.
=> Enable facilitator to edit individual assessment after workshop has started

backend/api/GQL/Mutation.cs, backend/api/Migrations/20210709134613_WorkshopSummary.Designer.cs, backend/api/Migrations/20210709134613_WorkshopSummary.cs, backend/api/Models/Models.cs, backend/api/Services/EvaluationService.cs, backend/api/Services/QuestionTemplateService.cs, backend/tests/Services/EvaluationService.cs, backend/tests/Services/QuestionTemplateService.cs, frontend/src/api/fragments.ts, frontend/src/api/models.ts, frontend/src/api/mutations.ts, frontend/src/views/Evaluation/EvaluationView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopSummary.tsx, frontend/src/views/Evaluation/Workshop/WorkshopSummaryContainer.tsx, frontend/src/views/Evaluation/Workshop/WorkshopTabs.tsx
A couple of points worth nothing:
- Currently _only_ the facilitators can modify the summary
- The summary field is a string on the ``Evaluation``. I.e. we have no timestamps or record of authors. 
Closes #439
=> Workflow summary for facilitators

backend/api/Startup.cs, frontend/cypress/integration/actions_spec.ts, frontend/cypress/integration/create_evaluation_spec.ts, frontend/cypress/integration/sample_seed.ts, frontend/cypress/integration/sample_spec.ts, frontend/cypress/plugins/index.js, frontend/cypress/support/common.ts, frontend/cypress/support/external.ts, frontend/cypress/support/visit.ts
closes #497 (but still might want to create a separate issue in Cypress?)
=> Stability improvements

frontend/cypress/support/visit.ts
Apparently last attempt to solve it didn't manage to do it completely.
Here goes new attempt:
1. Before waiting for "Loading" to disappear check if we are not on
Evaluations page already. It looks like in rare cases page is loaded
before we start checking for "Loading" sign.
2. Simulate fusion (again) by saving project information in cache. That
seems to solve the problem of project not being loaded on navigation and
"Please select a project" label persisting.
=> Stabilize page visit

README.md, backend/api/Startup.cs, docker-compose.cypress.yml, frontend/Dockerfile, frontend/cypress.Dockerfile, frontend/cypress.json, frontend/cypress/README.md, frontend/cypress/plugins/index.js, frontend/cypress/support/auth.ts, frontend/cypress/support/gql.ts, frontend/cypress/support/visit.ts, frontend/package-lock.json, frontend/package.json, pipelines/azure-pipelines.yml, pipelines/cypress-E2E.yml
closes #466
- Add Cypress E2E on PR builds
=> Add Cypress to CI

backend/api/GQL/Mutation.cs, backend/api/Migrations/20210811110505_AddWorkshopCompleteDate.Designer.cs, backend/api/Migrations/20210811110505_AddWorkshopCompleteDate.cs, backend/api/Models/Models.cs, backend/api/Services/EvaluationService.cs, backend/tests/Services/EvaluationService.cs, frontend/src/api/fragments.ts, frontend/src/api/models.ts, frontend/src/views/Evaluation/EvaluationGQL.ts, frontend/src/views/Evaluation/FollowUp/Summaries/BowtieView.tsx, frontend/src/views/Evaluation/FollowUp/Summaries/WorkshopSummaryView.tsx
=> Save workshop finishing date in the database

frontend/package-lock.json, frontend/package.json
- Performance fixes for video creation
- Working Test Runner menu
=> Update cypress to 8.3.0

frontend/src/api/error.ts, frontend/src/components/Action/CreateForm/ActionCreateForm.tsx, frontend/src/components/Action/CreateForm/ActionCreateSidebar.tsx, frontend/src/components/Action/CreateForm/ActionCreateSidebarWithApi.tsx, frontend/src/components/Action/EditForm/ActionEditSidebar.tsx, frontend/src/components/Action/EditForm/ActionEditSidebarWithApi.tsx, frontend/src/components/Action/EditForm/NoteCreateForm.tsx, frontend/src/components/QuestionAndAnswer/QuestionAndAnswerFormWithApi.tsx, frontend/src/views/Evaluation/EvaluationRoute.tsx, frontend/src/views/Evaluation/Nomination/NominationView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopSummaryContainer.tsx, frontend/src/views/Project/Dashboard/CreateEvaluationButton.tsx, frontend/src/views/Project/Dashboard/CreateEvaluationDialog.tsx, frontend/src/views/Project/Dashboard/ProjectDashboardView.tsx, frontend/src/views/Project/ProjectRoute.tsx
=> Don't show Apollo errors in UI

README.md
=> Add badges for radix pipelines to README

frontend/cypress/support/mock/external/external.ts
=> Cypress empty promise

docker-compose.cypress.yml, frontend/cypress.Dockerfile, pipelines/cypress-E2E.yml
=> Add git information to cypress builds

frontend/src/views/Admin/BarrierQuestionList.tsx
=> Add key to BarrierQuestionList

frontend/cypress/integration/actions_spec.ts, frontend/cypress/support/action.ts, frontend/src/components/Action/EditForm/NotesAndClosingRemarksList.tsx
This is a new version of test actions list after the previous PR became big and the merge conflict with Petters refactoring became too big. I think I will make this in two PRs to make it more manageable: 
* This PR will contain the refactoring of the completed test. It will consider the comments from Alenas PR that came after the merge, and the relevant comments for the other PR. Mainly, it will refactor the test, but I think I also added some extra checks (mostly if a closing note is present)
* The next PR will contain the actual tests for action list.
Maybe somebody can also help me find out why the tests still fail
=> Refactoring complete-tests

frontend/package-lock.json, frontend/package.json, frontend/src/components/Action/CreateForm/ActionCreateForm.tsx, frontend/src/components/Action/EditForm/NoteCreateForm.tsx, frontend/src/components/Action/QuestionActionsList.tsx, frontend/src/components/StatusTab.tsx, frontend/src/components/StyledTabs.tsx, frontend/src/views/Admin/AdminView.tsx, frontend/src/views/Admin/QuestionTemplateMenu.tsx, frontend/src/views/Admin/StaticQuestionItem.tsx, frontend/src/views/Evaluation/FollowUp/FollowUpStepView.tsx, frontend/src/views/Evaluation/Workshop/WorkshopTabs.tsx, frontend/src/views/Project/ProjectRoute.tsx
It now looks like this when you click the menu-button:
**Some notes:**
* I had to upgrade the equinor-design-system-package from 0.8 to 0.13 to get a Menu-component that worked. We should check if it's ok to merge that. Because of the package change I had to make a change to the naming of some tab-elements, Tooltip, and some small styling changes (margins that suddenly were lacking). That is actually most of the files in this PR.
* The buttons in the menu are not yet implemented, as that was not part of the issue.
* The menu gets a strange dashed line around the menu element when an element is clicked. I think this has to do with keyboard-control / accessability, but I don't think it's possible to remove (and anyways we probably shouldn't)?
=> Made menu for question template

frontend/src/views/Admin/AdminQuestionItem.tsx, frontend/src/views/Admin/AdminView.tsx, frontend/src/views/Admin/QuestionListWithApi.tsx, frontend/src/views/Admin/StaticQuestionItem.tsx
=> Added tags for project category

pipelines/cypress-E2E.yml
=> Add sleep to E2E pipeline

backend/Dockerfile, frontend/Dockerfile, pipelines/ArtifactBuild.yml, radixconfig.yaml
Modified the Dockerfile to retrieve dynatrace OneAgent, and added new
environment in Radix to retrieve image from ACR #541
=> Adding dynatrace to dockerfile and new radix env

README.md, docker-compose.dynatrace.yml, radixconfig.yaml
- addded docker config to pipeline
- Update readme with which database to use for test migrations
- Create docker-compose for Dynatrace docker images
=> Add docker compose for dynatrace oneAgent

backend/api/GQL/Mutation.cs, backend/api/Migrations/20210107073235_InitialCreate.cs, backend/api/Migrations/20210114083549_AddStatusToEvaluation.cs, backend/api/Migrations/20210209104023_DateTimeOffsetAndOrderQuestion.cs, backend/api/Migrations/20210719093231_EvaluationSummary.cs, backend/api/Migrations/20210719094100_PreviousEvaluationId.cs, backend/api/Migrations/20210811110505_AddWorkshopCompleteDate.cs, backend/api/Migrations/20210824121302_AddClosingRemarksTable.cs, backend/api/Migrations/20210915135241_AddProjectCategory.cs, backend/api/Services/ProjectCategoryService.cs, backend/api/Startup.cs, frontend/cypress/auth_server/config.json
This can only be performed by Admins defined in Azure
AD, controlled by the group FUSION - BMT Administrator
closes #636
=> Add authorization to admin mutation

frontend/cypress/support/evaluation_seed.ts
Solves #638 
For me some parts of the documentation are useful, and I took away the parts the specify how the method works (and can be read in the code itself).
=> Remove doc about how seed and plant works, let what it is

pipelines/ArtifactBuild.yml
Changing endpoint since we both deploy a new image, and build existing
apps.
=> Changing api endpoint to  build and deploy

pipelines/ArtifactBuild.yml
Moved the api trigger from backend phase to own stage where its
dependent on frontend and backend. #852
=> Added trigger radix as new stage

pipelines/cypress-E2E.yml
Setting the value of name to buildname, buildid and revnr. #812
=> Adding name to yaml to add rev nr to buildid

frontend/cypress/integration/admin_page_spec.ts, frontend/cypress/page_objects/admin_page.ts, frontend/cypress/support/testsetup/gql.ts
=> Add cypress test to delete all project categories from question template

pipelines/ArtifactBuild.yml, pipelines/templates/stage-deploy-approval.yml, pipelines/templates/stage-deploy-backend.yml, pipelines/templates/stage-deploy-frontend.yml, pipelines/templates/stage-trigger-radix.yml
Use templates for stages, which enables code reusabillity, increased
readabillity and ensures identical pipeline for each environment. #857
=> Adding templates to increase readabillity

frontend/package-lock.json, frontend/package.json
Downgrade Cypress from 8.7 to 8.4 as videos no longer work in 8.7
=> Downgrade Cypress from 8.7 to 8.4

frontend/cypress/integration/actions_spec.ts, frontend/cypress/integration/landing_page_spec.ts, frontend/cypress/page_objects/action.ts, frontend/cypress/testdata/actions.ts
Add Cypress test for edit action from actions-table accessed from
- follow up
- landing page
=> Add Cypress test to edit function from action table

frontend/src/views/Admin/CreateQuestionItem.tsx, frontend/src/views/Admin/EditableQuestionItem.tsx
=> Align title and organization in edit mode

frontend/src/utils/hooks.ts, frontend/src/views/Project/Dashboard/Portfolios.tsx, frontend/src/views/Project/Dashboard/ProjectDashboardView.tsx, frontend/src/views/Project/Dashboard/TablesAndTitles.tsx
=> Sort evaluations by project master

frontend/cypress/integration/view_answers_spec.ts, frontend/cypress/page_objects/evaluation.ts
=> View answers follow up and workshop summary

pipelines/ArtifactBuild.yml, pipelines/templates/stage-deploy.yml, pipelines/templates/stage-trigger-radix.yml
Replacing Radix trigger with powershell to start build-deploy, and
another task to wait for the build-deploy to finish. #931
=> Adding delay and retry for radix build-deploy job

frontend/cypress/integration/landing_page_spec.ts, frontend/src/views/Project/Dashboard/Components/TablesAndTitles.tsx
=> Use Accordion for project master titles

frontend/cypress/auth_server/config.json, frontend/cypress/integration/evaluation_spec.ts, frontend/cypress/support/mock/external/users.ts
=> Revise Cypress tests only AccessIT role facilitator can create evals

frontend/src/views/Project/Dashboard/Components/CreateEvaluationButton.tsx, frontend/src/views/Project/Dashboard/DashboardView.tsx
=> Add link to Project Development Centre

backend/api/api.csproj
- Upgrade backend dependencies
- Update Identity web to 1.21.1
=> Update identity web

frontend/dynatrace.Dockerfile, pipelines/ArtifactBuild.yml, pipelines/templates/stage-deploy.yml
Remove radix token for auth and replaced with service principal
=> Removing Radix Token

radixconfig.yaml
Removed component and forgot to update dnsappalias
=> Removed wrong component reference

frontend/Dockerfile
Add missing dynatrace config to Dockerfile extra
=> Add dynatrace config to dockerfile

pipelines/templates/stage-deploy.yml
Add specific dotnet to deploy pipeline for db migrations
=> Add version to db migration step

pipelines/templates/stage-deploy.yml, radixconfig.yaml
Dynatrace variables missing from Dockercontainer
=> Add env variables to containers

pipelines/templates/stage-deploy.yml
Add step to install dotnet v5.0 to the db migrations job in Pipelines
=> Add dotnetsdk to migrations

pipelines/templates/stage-deploy.yml
Error in command to install v5 of dotnet sdk
=> Fix typo in pipeline

frontend/dynatrace.Dockerfile
Add folder for npm cache to env variable, create folder and set correct
permission on said folder.
=> Add npm cache config

pipelines/ArtifactBuild.yml
Fusion changes url for platform, and we need to change from hardcoded value to environment variable
=> fix: Url Change in Fusion

frontend/src/styles.css, frontend/src/views/Project/Dashboard/Components/CreateEvaluationButton.tsx
- Added updated eds url to styles.css
=> feat: Update eds url in styles.css

backend/api/Helpers/RequestLoggingMiddleware.cs, backend/api/Program.cs, backend/api/api.csproj, backend/api/appsettings.json
Add serilog feature, config and loggingmiddleware to api
=> feat: Add serilog to backend

frontend/src/utils/actionUtils.ts, frontend/src/views/Evaluation/EvaluationView.tsx
=> fix: Remove cancelled overdue-actions from dashboardview

backend/api/GQL/Mutation.cs, frontend/src/components/EvaluationScoreIndicator.tsx, frontend/src/utils/helpers.ts, frontend/src/views/Project/Dashboard/Components/TablesAndTitles.tsx
Remove indicator activity for finished evaluations
=> fix: Allow setting finished evaluations as indicator
